name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: lkiesow/setup-lxc-container@v1
        id: lxc
        with:
          dist: debian
          release: trixie
          python: false

      - name: IP address
        run: |
          echo 'Container IP address: ${{ steps.lxc.outputs.ip }}'

      - name: Test SSH
        run: |
          ssh test echo success
          
      - name: Install drill
        run: |
          ssh test apt-get install -y ldnsutils
          
      - name: Drill home
        run: |
          ssh test drill henku.de
          
      - name: Create and push file into lxc container
        run: |
          echo "Hello lxc container" > test.txt
          lxc file push -p text.txt test/tmp/

      - name: Say hello
        run: |
          ssh cat /tmp/text.txt
